$seedPath = "c:\Goombi\goombi-mvp\backend\app\data\listings.json"
$timestamp = "2026-05-30T00:00:00+02:00"

function To-Slug([string]$value) {
    $slug = $value.ToLowerInvariant() -replace "[^a-z0-9]+", "-"
    $slug = $slug.Trim("-")
    return $slug
}

$rows = @(
    @{ name="Lebo's Soweto Backpackers"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Orlando West"; address="Vilakazi Street, Orlando West, Soweto"; latitude=-26.2644; longitude=27.8558; price_per_night=450; guest_capacity=20; bathrooms=4; verified_status=$true; description="Iconic Soweto guesthouse on Vilakazi Street. Award-winning backpackers offering cycling tours, shisa nyama and authentic township experience. The most famous guesthouse in Soweto."; tags=@("Cycling tours","Vilakazi Street","Shisa nyama","Award-winning","Bicycle hire"); nearby_attractions=@("Mandela House Museum","Hector Pieterson Museum","Vilakazi Street","Orlando Towers") }
    @{ name="Soweto Hotel at Freedom Square"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Kliptown"; address="Freedom Square, Kliptown, Soweto"; latitude=-26.2741; longitude=27.8647; price_per_night=1800; guest_capacity=4; bathrooms=2; verified_status=$true; description="Boutique hotel in the heart of Kliptown where the Freedom Charter was signed. Rooftop restaurant with panoramic Soweto views and a rich political heritage."; tags=@("Freedom Charter","Rooftop restaurant","Heritage","Kliptown","Political history"); nearby_attractions=@("Walter Sisulu Square","Kliptown Open Air Market","Freedom Charter Monument") }
    @{ name="Ubuntu Bed & Breakfast"; township_type="bnb"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Orlando East"; address="Orlando East, Soweto"; latitude=-26.2533; longitude=27.8789; price_per_night=680; guest_capacity=6; bathrooms=2; verified_status=$true; description="Family-run B&B in Orlando East offering authentic Soweto hospitality. Home-cooked South African breakfast included. Walking distance to Orlando Stadium."; tags=@("Home-cooked breakfast","Family-run","Ubuntu spirit","Orlando Stadium nearby"); nearby_attractions=@("Orlando Stadium","Soweto Theatre","Regina Mundi Church") }
    @{ name="Mayfair Soweto Guesthouse"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Mayfair"; address="Mayfair, Johannesburg"; latitude=-26.2167; longitude=27.9833; price_per_night=850; guest_capacity=8; bathrooms=3; verified_status=$true; description="Comfortable guesthouse on the border of Mayfair and Soweto. Traditional South Asian-African fusion cuisine reflecting the diverse cultural heritage of the area."; tags=@("Cultural fusion","South Asian heritage","Traditional cuisine","Safe neighbourhood"); nearby_attractions=@("Apartheid Museum","Gold Reef City","Mayfair Bazaar") }
    @{ name="Maboneng City Lodge"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Maboneng"; address="Maboneng Precinct, Johannesburg"; latitude=-26.2025; longitude=28.0572; price_per_night=1200; guest_capacity=4; bathrooms=2; verified_status=$true; description="Stylish urban guesthouse in Johannesburg's creative Maboneng precinct. Art galleries, rooftop bars and the famous Market on Main all within walking distance."; tags=@("Art galleries","Creative district","Urban cool","Market on Main","Rooftop bars"); nearby_attractions=@("Market on Main","Arts on Main","Neighbourgoods Market JHB") }
    @{ name="Eyethu Township Guest House"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Dobsonville"; address="Dobsonville, Soweto"; latitude=-26.2389; longitude=27.8244; price_per_night=550; guest_capacity=6; bathrooms=2; verified_status=$false; description="Authentic Soweto guesthouse run by a local family. Traditional pap and vleis dinners on request. Experience real township life in a safe and welcoming environment."; tags=@("Authentic","Family-run","Traditional food","Township life"); nearby_attractions=@("Eyethu Lifestyle Centre","Soweto Brewing Company") }
    @{ name="Alexandra Township B&B"; township_type="bnb"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Alexandra"; address="Alexandra, Johannesburg"; latitude=-26.1000; longitude=28.0833; price_per_night=480; guest_capacity=4; bathrooms=1; verified_status=$false; description="Simple and authentic B&B in Alexandra township, one of Johannesburg's oldest townships. Close to the Sandton business district - township experience meets corporate convenience."; tags=@("Alexandra","Close to Sandton","Authentic","Budget-friendly"); nearby_attractions=@("Alexandra Heritage Centre","Pan Africa Market") }
    @{ name="Vilakazi Street Guesthouse"; township_type="guesthouse"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Orlando West"; address="Vilakazi Street, Orlando West, Soweto"; latitude=-26.2651; longitude=27.8563; price_per_night=950; guest_capacity=6; bathrooms=2; verified_status=$true; description="On the world-famous street that housed two Nobel Peace Prize winners. Comfortable rooms with historical ambience and guided walking tours of the street included."; tags=@("Vilakazi Street","Nobel laureates","Guided tours","Historical","Premium location"); nearby_attractions=@("Mandela House Museum","Desmond Tutu House","Hector Pieterson Museum") }

    @{ name="Mandela House Museum"; township_type="attraction"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Orlando West"; address="Vilakazi Street, Orlando West, Soweto"; latitude=-26.2643; longitude=27.8558; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Nelson Mandela's former home, now a museum filled with personal memorabilia. Essential visit for understanding South Africa's struggle for freedom."; tags=@("Museum","Nelson Mandela","Heritage","History","Must-visit"); nearby_attractions=@("Hector Pieterson Museum","Vilakazi Street","Orlando Towers") }
    @{ name="Hector Pieterson Museum"; township_type="attraction"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Orlando West"; address="8287 Khumalo Street, Orlando West, Soweto"; latitude=-26.2658; longitude=27.8542; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Profoundly moving tribute to student activism and the 1976 Soweto Uprising. Documents the bravery of young people who changed the course of South African history."; tags=@("Museum","1976 Uprising","History","Apartheid","Memorial"); nearby_attractions=@("Mandela House Museum","Vilakazi Street","Regina Mundi Church") }
    @{ name="Orlando Towers"; township_type="attraction"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Klipspruit"; address="Chris Hani Road, Klipspruit, Soweto"; latitude=-26.2750; longitude=27.8611; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Iconic painted cooling towers with bungee jumping, base jumping, and Chaf Jozi shisa nyama restaurant. Soweto's most thrilling landmark."; tags=@("Bungee jumping","Landmark","Shisa nyama","Adventure","Iconic"); nearby_attractions=@("Vilakazi Street","Mandela House Museum","Walter Sisulu Square") }
    @{ name="Soweto Theatre"; township_type="attraction"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Jabulani"; address="Bolani Link, Jabulani, Soweto"; latitude=-26.2556; longitude=27.8400; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Premier arts venue hosting theatre, jazz and comedy performances. Monthly arts and crafts fair. Architecturally stunning building worth visiting on its own."; tags=@("Theatre","Jazz","Comedy","Arts fair","Architecture"); nearby_attractions=@("Orlando Stadium","Regina Mundi Church","Vilakazi Street") }
    @{ name="Regina Mundi Catholic Church"; township_type="attraction"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Rockville"; address="Mkhize Street, Rockville, Soweto"; latitude=-26.2728; longitude=27.8867; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Soweto's largest church, used as a refuge and meeting point during the 1976 uprising. Bullet holes still visible. An emotionally powerful heritage site."; tags=@("Church","Heritage","1976 Uprising","Apartheid history","Architecture"); nearby_attractions=@("Hector Pieterson Museum","Orlando Stadium","Soweto Theatre") }
    @{ name="Market on Main"; township_type="market"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Maboneng"; address="Arts on Main, Maboneng, Johannesburg"; latitude=-26.2033; longitude=28.0578; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Johannesburg's most celebrated Sunday market in the creative Maboneng precinct. Street food, art, vintage clothing, live music and local designers every Sunday."; tags=@("Sunday market","Street food","Art","Vintage","Live music"); nearby_attractions=@("Arts on Main","Maboneng Precinct","Neighbourgoods Market JHB") }
    @{ name="Credo Mutwa Cultural Village"; township_type="cultural_centre"; region="Gauteng"; province="Gauteng"; city="Johannesburg"; suburb="Soweto"; address="Soweto, Johannesburg"; latitude=-26.2589; longitude=27.8633; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$false; description="Traditional African cultural heritage village showcasing San and African mythology, sculptures and artifacts created by Vusamazulu Credo Mutwa, Africa's greatest living storyteller."; tags=@("Cultural village","African mythology","Sculptures","Traditional","San heritage"); nearby_attractions=@("Orlando Towers","Vilakazi Street","Hector Pieterson Museum") }

    @{ name="Vicky's B&B"; township_type="bnb"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0352; longitude=18.6731; price_per_night=650; guest_capacity=4; bathrooms=1; verified_status=$true; description="Award-winning B&B run by Vicky who has welcomed visitors from over 50 countries. Authentic Khayelitsha experience with home-cooked breakfast and guided community walks."; tags=@("Award-winning","50+ countries","Home-cooked breakfast","Community walks","Authentic"); nearby_attractions=@("Makukhanye Art Room","Khayelitsha Wetlands","18 Gangster Museum") }
    @{ name="Majoro's Khayelitsha Guesthouse"; township_type="guesthouse"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0389; longitude=18.6756; price_per_night=580; guest_capacity=6; bathrooms=2; verified_status=$true; description="Welcoming township guesthouse in Khayelitsha. Majoro hosts cooking classes, shebeen tours and community garden visits. Rated one of Cape Town's most unique stays."; tags=@("Cooking classes","Shebeen tours","Community garden","Unique experience"); nearby_attractions=@("Abalimi Garden","Khayelitsha Wines","Siki's Coffee") }
    @{ name="Langa Township Guesthouse"; township_type="guesthouse"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Langa"; address="Langa, Cape Town"; latitude=-33.9464; longitude=18.5258; price_per_night=520; guest_capacity=4; bathrooms=1; verified_status=$true; description="Stay in Cape Town's oldest township, founded in 1927. Your host will take you on a walking tour of Langa's historic streets, shebeens and the famous Pass Museum."; tags=@("Oldest township","Walking tours","Pass Museum","Historic","Local guide"); nearby_attractions=@("Langa Pass Museum","Langa Arts Quarter","Guga S'thebe Culture Centre") }
    @{ name="Gugulethu Ubuntu Lodge"; township_type="cultural_lodge"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Gugulethu"; address="Gugulethu, Cape Town"; latitude=-33.9900; longitude=18.5733; price_per_night=780; guest_capacity=6; bathrooms=2; verified_status=$true; description="Cultural lodge in the heart of Gugulethu offering immersive township experiences. Mzoli's famous shisa nyama is a short walk away. Jazz evenings and art tours arranged."; tags=@("Cultural lodge","Jazz","Art tours","Mzoli's nearby","Immersive"); nearby_attractions=@("Mzoli's Place","Guga S'thebe Culture Centre","Gugulethu Seven Memorial") }
    @{ name="Bo-Kaap Heritage House"; township_type="guesthouse"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Bo-Kaap"; address="Bo-Kaap, Cape Town"; latitude=-33.9244; longitude=18.4139; price_per_night=1800; guest_capacity=4; bathrooms=2; verified_status=$true; description="Stay in one of Cape Town's iconic cobblestone street houses in the historic Bo-Kaap (Cape Malay Quarter). Traditional Cape Malay cuisine and mountain views."; tags=@("Bo-Kaap","Cape Malay","Cobblestone streets","Heritage","Mountain views"); nearby_attractions=@("Bo-Kaap Museum","Signal Hill","Nurul Islam Mosque") }
    @{ name="Khayelitsha Wellness Lodge"; township_type="cultural_lodge"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0411; longitude=18.6789; price_per_night=720; guest_capacity=8; bathrooms=2; verified_status=$false; description="Community-owned lodge combining township hospitality with wellness. Traditional healing, herbal gardens and Xhosa cultural experiences. Profits support local youth programmes."; tags=@("Community-owned","Wellness","Traditional healing","Xhosa culture","Social impact"); nearby_attractions=@("Khayelitsha Wetlands","Makukhanye Art Room","Khayelitsha Wines") }
    @{ name="District Six Guesthouse"; township_type="guesthouse"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Zonnebloem"; address="Zonnebloem, Cape Town"; latitude=-33.9311; longitude=18.4289; price_per_night=1200; guest_capacity=4; bathrooms=2; verified_status=$true; description="Stay adjacent to the historic District Six, where 60,000 people were forcibly removed during apartheid. The District Six Museum is a 5-minute walk from your door."; tags=@("District Six","Heritage","Museum nearby","Historical","Apartheid history"); nearby_attractions=@("District Six Museum","Bo-Kaap","Greenmarket Square") }

    @{ name="18 Gangster Museum"; township_type="attraction"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0367; longitude=18.6744; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Africa's first living museum about gangsterism, curated by former offenders. An immersive, powerful experience educating youth about the pitfalls of gangsterism and drugs."; tags=@("Museum","Living museum","Social impact","Unique","Educational"); nearby_attractions=@("Makukhanye Art Room","Khayelitsha Wines","Siki's Coffee") }
    @{ name="Langa Pass Museum"; township_type="attraction"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Langa"; address="Langa, Cape Town"; latitude=-33.9456; longitude=18.5244; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Documents the powerful political history of the pass laws. Langa was home to a 50,000-strong protest march against apartheid pass laws. Essential heritage site."; tags=@("Museum","Pass laws","Apartheid history","Heritage","Political history"); nearby_attractions=@("Guga S'thebe Culture Centre","Langa Arts Quarter","Langa Township Guesthouse") }
    @{ name="Guga S'thebe Culture Centre"; township_type="cultural_centre"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Langa"; address="Washington Street, Langa, Cape Town"; latitude=-33.9478; longitude=18.5267; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Vibrant community arts centre named after the traditional Xhosa serving platter. Signifies Ubuntu as a meeting place for creative exchange, performances and exhibitions."; tags=@("Culture centre","Xhosa","Ubuntu","Arts","Performances"); nearby_attractions=@("Langa Pass Museum","Langa Arts Quarter","Langa Township Guesthouse") }
    @{ name="Mzoli's Place"; township_type="restaurant"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Gugulethu"; address="NY 115, Gugulethu, Cape Town"; latitude=-33.9922; longitude=18.5711; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Cape Town's most famous township butchery and tavern. Choose your meat, Mzoli's team grills it on the braai while you enjoy music and community atmosphere."; tags=@("Shisa nyama","Butchery","Braai","Iconic","Community atmosphere"); nearby_attractions=@("Gugulethu Seven Memorial","Guga S'thebe Culture Centre","Gugulethu Ubuntu Lodge") }
    @{ name="Makukhanye Art Room"; township_type="cultural_centre"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0378; longitude=18.6722; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Vibrant community art space showcasing township artists and youth creative development. Colourful murals, workshops and exhibitions celebrating Khayelitsha's creative spirit."; tags=@("Art","Youth development","Murals","Workshops","Community"); nearby_attractions=@("18 Gangster Museum","Khayelitsha Wines","Siki's Coffee") }
    @{ name="Khayelitsha Wines"; township_type="attraction"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0395; longitude=18.6758; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Unique township winery breaking stereotypes about wine culture in South Africa. Wine tastings in a township setting - an experience unlike anywhere else in the world."; tags=@("Wine tasting","Unique","Township experience","Entrepreneurship"); nearby_attractions=@("Makukhanye Art Room","Siki's Coffee","18 Gangster Museum") }
    @{ name="Siki's Coffee"; township_type="restaurant"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Khayelitsha"; address="Khayelitsha, Cape Town"; latitude=-34.0382; longitude=18.6741; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Township coffee shop celebrating local entrepreneurship and youth empowerment. Fresh brews, local pastries and great conversations in the heart of Khayelitsha."; tags=@("Coffee","Youth empowerment","Entrepreneurship","Local"); nearby_attractions=@("Makukhanye Art Room","Khayelitsha Wines","18 Gangster Museum") }
    @{ name="District Six Museum"; township_type="attraction"; region="Western Cape"; province="Western Cape"; city="Cape Town"; suburb="Zonnebloem"; address="25A Buitenkant Street, Zonnebloem, Cape Town"; latitude=-33.9308; longitude=18.4283; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="World-renowned museum documenting the forced removal of 60,000 inhabitants during the 1970s. One of Cape Town's most important and moving heritage sites."; tags=@("Museum","Forced removals","Apartheid","Heritage","World-renowned"); nearby_attractions=@("Bo-Kaap Museum","Greenmarket Square","District Six Guesthouse") }

    @{ name="Inanda Heritage Lodge"; township_type="cultural_lodge"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Inanda"; address="Inanda Heritage Route, Durban"; latitude=-29.7167; longitude=30.9333; price_per_night=850; guest_capacity=6; bathrooms=2; verified_status=$true; description="Cultural lodge on the Inanda Heritage Route. Walk in the footsteps of Gandhi, Mandela and John Dube. Guided heritage tours, traditional Zulu meals and drumming evenings."; tags=@("Heritage route","Gandhi","Mandela","Zulu culture","Guided tours"); nearby_attractions=@("Gandhi Settlement","Ohlange Institute","Inanda Dam","Shembe Church") }
    @{ name="Umlazi Township Guesthouse"; township_type="guesthouse"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Umlazi"; address="Umlazi, Durban"; latitude=-29.9667; longitude=30.8833; price_per_night=580; guest_capacity=4; bathrooms=2; verified_status=$true; description="Comfortable guesthouse in Umlazi, the second largest township in South Africa. Your host arranges traditional Zulu dance performances and shisanyama experiences."; tags=@("Zulu dance","Shisanyama","Authentic","Local guide","Umlazi"); nearby_attractions=@("Max's Lifestyle Village","Princess Magogo Stadium","Mxenge Museum") }
    @{ name="KwaMashu Community Guesthouse"; township_type="guesthouse"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="KwaMashu"; address="KwaMashu, Durban"; latitude=-29.7500; longitude=30.9667; price_per_night=490; guest_capacity=4; bathrooms=1; verified_status=$false; description="Stay in KwaMashu, Durban's oldest township, renowned for its vibrant performance arts scene. Hip-hop, pantsula dancing and kwaito music form the soundtrack of daily life."; tags=@("Performance arts","Hip-hop","Pantsula","Kwaito","Authentic"); nearby_attractions=@("KwaMashu Arts Centre","INK Heritage Route","KwaMashu Performance Arts Centre") }
    @{ name="Valley of 1000 Hills Lodge"; township_type="cultural_lodge"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Drummond"; address="Valley of 1000 Hills, Drummond"; latitude=-29.7833; longitude=30.7167; price_per_night=1200; guest_capacity=8; bathrooms=3; verified_status=$true; description="Cultural lodge in the breathtaking Valley of a Thousand Hills. Traditional Zulu village visits, cultural performances, zip-lining and spectacular views of the valley."; tags=@("Zulu village","Cultural performances","Zip-lining","Scenic","1000 Hills"); nearby_attractions=@("PheZulu Safari Park","Assagay Valley","Zulu cultural village") }
    @{ name="eNanda Adventure Camp"; township_type="cultural_lodge"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Inanda"; address="Inanda Dam, Durban"; latitude=-29.7056; longitude=30.9011; price_per_night=750; guest_capacity=10; bathrooms=3; verified_status=$true; description="Camping on the water's edge at Inanda Dam. Hiking to Mzinyathi Falls, canoeing, fishing and birdwatching with deep historical heritage around every corner."; tags=@("Camping","Inanda Dam","Canoeing","Hiking","Mzinyathi Falls"); nearby_attractions=@("Inanda Dam","Mzinyathi Falls","Inanda Heritage Route") }
    @{ name="Clermont Ubuntu B&B"; township_type="bnb"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Clermont"; address="Clermont, Durban"; latitude=-29.8167; longitude=30.8833; price_per_night=420; guest_capacity=4; bathrooms=1; verified_status=$false; description="Budget-friendly B&B in Clermont township. Authentic Zulu hospitality, home-cooked meals and a genuine community experience within easy reach of Durban city centre."; tags=@("Budget","Zulu hospitality","Home-cooked","Authentic","Community"); nearby_attractions=@("Clermont War Memorial","Local spaza shops","Inanda Heritage Route") }
    @{ name="Durban Indian Quarter Guesthouse"; township_type="guesthouse"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Grey Street"; address="Grey Street, Durban"; latitude=-29.8578; longitude=31.0178; price_per_night=780; guest_capacity=4; bathrooms=2; verified_status=$true; description="Stay in the heart of Durban's vibrant Indian Quarter, home to the largest Indian population outside India. Victoria Street Market, curry houses and mosques steps away."; tags=@("Indian Quarter","Victoria Street Market","Curry","Cultural diversity","Grey Street"); nearby_attractions=@("Victoria Street Market","Juma Mosque","Emmanuel Cathedral") }

    @{ name="Inanda Heritage Route"; township_type="attraction"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Inanda"; address="Inanda Heritage Route, Durban"; latitude=-29.7167; longitude=30.9333; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Historic trail starting at Gandhi's Phoenix Settlement, passing Inanda Seminary, Ohlange Institute (where Mandela voted in 1994) and the Shembe Church at Ebuhleni."; tags=@("Gandhi","Mandela","Heritage route","ANC history","Multi-site"); nearby_attractions=@("Gandhi Settlement","Ohlange Institute","Shembe Church") }
    @{ name="Shembe Church (Nazareth Baptist Church)"; township_type="attraction"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Ebuhleni"; address="Ebuhleni, Inanda, Durban"; latitude=-29.6833; longitude=30.9667; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Declared a world heritage site. The Shembe Church is a remarkable blend of Zulu tradition and Christian faith with elaborate rituals and vibrant gospel culture."; tags=@("World heritage","Shembe","Zulu religion","Cultural","Spiritual"); nearby_attractions=@("Inanda Heritage Route","Gandhi Settlement","Ohlange Institute") }
    @{ name="Mxenge Museum"; township_type="attraction"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Umlazi"; address="Umlazi, Durban"; latitude=-29.9722; longitude=30.8811; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Former home of struggle icons Advocate Griffiths and Victoria Mxenge, both killed fighting apartheid. A powerful reminder of the price of freedom."; tags=@("Museum","Struggle heroes","Apartheid","Heritage","Human rights"); nearby_attractions=@("Max's Lifestyle Village","Princess Magogo Stadium","Umlazi Township Guesthouse") }
    @{ name="Max's Lifestyle Village"; township_type="restaurant"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Umlazi"; address="V Section, Umlazi, Durban"; latitude=-29.9689; longitude=30.8844; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Umlazi's most celebrated restaurant. Traditional kasi culture in upmarket, safe surroundings. People from all walks of life come for the food, music and township atmosphere."; tags=@("Restaurant","Kasi culture","Township dining","Music","Famous"); nearby_attractions=@("Mxenge Museum","Princess Magogo Stadium","Umlazi Township Guesthouse") }
    @{ name="Victoria Street Market"; township_type="market"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Durban CBD"; address="151/155 Victoria Street, Durban"; latitude=-29.8572; longitude=31.0175; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Durban's oldest and most vibrant market selling spices, traditional medicine, curios, clothing and fresh produce. The beating heart of Durban's Indian and Zulu trading culture."; tags=@("Market","Spices","Traditional medicine","Indian","Zulu","Historic"); nearby_attractions=@("Juma Mosque","Emmanuel Cathedral","Durban Indian Quarter") }
    @{ name="KwaMashu Performance Arts Centre"; township_type="cultural_centre"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="KwaMashu"; address="KwaMashu, Durban"; latitude=-29.7500; longitude=30.9644; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Hub of KwaMashu's world-renowned performance arts scene. Hip-hop, pantsula, gumboot dancing and kwaito performances celebrating the township's unique cultural identity."; tags=@("Performance arts","Hip-hop","Gumboot dancing","Pantsula","Kwaito"); nearby_attractions=@("INK Heritage Route","KwaMashu Community Guesthouse","Inanda Heritage Route") }
    @{ name="PheZulu Safari Park"; township_type="attraction"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Valley of 1000 Hills"; address="Old Main Road, Valley of 1000 Hills"; latitude=-29.7917; longitude=30.7361; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Traditional Zulu cultural village and wildlife experience in the Valley of a Thousand Hills. Zulu dancing, crocodiles, snakes and stunning valley views all in one."; tags=@("Zulu culture","Wildlife","Cultural village","Dancing","1000 Hills"); nearby_attractions=@("Valley of 1000 Hills Lodge","Assagay Valley","Zulu cultural village") }
    @{ name="Gandhi Settlement Phoenix"; township_type="attraction"; region="KwaZulu-Natal"; province="KwaZulu-Natal"; city="Durban"; suburb="Phoenix"; address="Phoenix Settlement, Inanda Road, Durban"; latitude=-29.6833; longitude=31.0000; price_per_night=$null; guest_capacity=$null; bathrooms=$null; verified_status=$true; description="Where Mahatma Gandhi established his passive resistance movement in South Africa in 1904. The Phoenix Settlement shaped Gandhi's philosophy of non-violent resistance."; tags=@("Gandhi","Heritage","Historical","Passive resistance","International significance"); nearby_attractions=@("Inanda Heritage Route","Ohlange Institute","Shembe Church") }
)

$townshipRecords = @()
foreach ($row in $rows) {
    $isTownshipStay = $row.township_type -in @("guesthouse", "bnb", "cultural_lodge")
    $id = "township-$(To-Slug $row.name)-01"
    $record = [ordered]@{
        id = $id
        name = $row.name
        category = "township"
        listing_type = "township"
        township_type = $row.township_type
        region = $row.region
        province = $row.province
        city = $row.city
        suburb = $row.suburb
        address = $row.address
        latitude = [double]$row.latitude
        longitude = [double]$row.longitude
        price_per_night = $row.price_per_night
        guest_capacity = $row.guest_capacity
        bathrooms = $row.bathrooms
        max_guests = $row.guest_capacity
        rooms = $row.bathrooms
        verified_status = [bool]$row.verified_status
        description = $row.description
        amenities = @()
        tags = $row.tags
        booking_url = $null
        nearby_attractions = $row.nearby_attractions
        township_tourism_relevant = $true
        owner_name = ""
        owner_phone = ""
        source_type = "manual_seed"
        partner_status = "seed"
        featured = $false
        created_at = $timestamp
        updated_at = $timestamp
    }

    if (-not $isTownshipStay) {
        $record.price_per_night = $null
        $record.guest_capacity = $null
        $record.bathrooms = $null
        $record.max_guests = $null
        $record.rooms = $null
    }

    $townshipRecords += $record
}

if ($townshipRecords.Count -ne 45) {
    throw "Expected 45 records, got $($townshipRecords.Count)"
}

$existing = Get-Content $seedPath -Raw | ConvertFrom-Json
$existingIds = @{}
foreach ($item in $existing) { $existingIds[$item.id] = $true }
foreach ($item in $townshipRecords) {
    if ($existingIds.ContainsKey($item.id)) {
        throw "Duplicate ID: $($item.id)"
    }
}

$raw = Get-Content $seedPath -Raw
$inner = ($townshipRecords | ConvertTo-Json -Depth 8)
$inner = $inner.Trim()
if ($inner.StartsWith("[")) { $inner = $inner.Substring(1) }
if ($inner.EndsWith("]")) { $inner = $inner.Substring(0, $inner.Length - 1) }
$inner = $inner.Trim()

if ($raw -notmatch "\]\s*$") {
    throw "Seed file does not end with a JSON array terminator."
}

$updated = [regex]::Replace($raw, "\]\s*$", ",`r`n$inner`r`n]", 1)
Set-Content -Path $seedPath -Value $updated -Encoding UTF8

Write-Host "Appended $($townshipRecords.Count) township records to seed."
